format_version: 3
pipelines:
  simple-go-server:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/siddhi1907/simple-go-server.git
        shallow_clone: false
        auto_update: true
        branch: master
    parameters:
      BRANCH: master
      VERSION: '1.0'
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            test:
              timeout: 5
              tasks:
                - exec:
                    arguments:
                      - '#{BRANCH} - #{VERSION}'
                    command: echo
                    run_if: passed
      - publish_version:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            publish_version:
              timeout: 5
              artifacts:
                - build:
                    source: 'simple-go-server.gocd.yaml'
                    destination: ''
                - build:
                    source: 'template.gocd.json'
                    destination: ''
                - build:
                    source: 'pipeline_setup.sh'
                    destination: ''
              tasks:
                - exec:
                    arguments:
                      - "-c"
                      - ./template.sh
                    command: bash
                    run_if: passed