- name: Install ldap authorisation plugin
  become: yes
  get_url:
    url: "https://github.com/gocd/gocd-ldap-authorization-plugin/releases/download/v4.0.1-6/gocd-ldap-authorization-plugin-4.0.1-6.jar"
    checksum: "sha256:ad0518af311b9879835d4f7121aca82e68fbb4fb488bdcf3437e8196413544de"
    dest: "/data/var-lib-go-server/plugins/external"
    mode: 0644
    owner: go
    group: go
  notify: "restart gocd server"

 - name: Install webhook notification plugin
   become: yes
   get_url:
     url: "{{ webhookNotificationPlugin.url }}"
     url_username: "{{ artifactoryAuthConfig.api_username }}"
     url_password: "{{ artifactoryAuthConfig.api_password }}"
     checksum: "{{ webhookNotificationPlugin.checksum }}"
     force_basic_auth: yes
     dest: "/data/go-server-work-dir/plugins/external"
     mode: 0644
     owner: go
     group: go
     validate_certs: no
   register: webhook_plugin

 - name: Generate configuration for GOCD webhook notification plugin
   become: yes
   template:
     src: "{{ item }}"
     dest: /data/go-server/config/{{ item }}
     owner: go
     group: go
     mode: 0440
   with_items:
     - notification.properties

 - name: Restart gocd server
   include_tasks: restart.yml
   vars:
     state: restarted
   when: ldap_plugin.changed or webhook_plugin.changed
