- name: Restart and enable go-server service
  become: yes
  systemd:
    name: go-server
    enabled: yes
    daemon-reload: yes
    state: "{{ state }}"
  register: service_state

- name: Wait for the GoCD server to start
  uri:
    url: http://127.0.0.1:8153/go/pipelines
    follow_redirects: yes
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  when: not ansible_check_mode and service_state.changed
  retries: 30
  delay: 2