format_version: 3
pipelines:
  testing-pipelines:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      Test-REPO:
        git: https://github.com/siddhi1907/testing-pipelines.git
        shallow_clone: false
        auto_update: true
        branch: master
    parameters:
      BRANCH: master
      VERSION: '1.0'
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            test:
              timeout: 5
              resources:
                - Linux
              tasks:
                - exec:
                    arguments:
                      - -c
                      - echo "Testing...."
                    command: /bin/bash
                    run_if: passed